name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres_db:
        image: postgres:13.1-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: parking
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}
        overwrite-settings: true
        job-status: 'success'
        
    - name: Build with Maven
      run: mvn clean install -B

    - name: Run Tests
      run: mvn test
